services:
  sjw-db:
    image: postgres:latest
    container_name: sjw-db
    environment:
      POSTGRES_DB: sjw_db
      POSTGRES_USER: seeder
      POSTGRES_PASSWORD: seeder
    ports:
      - "40911:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
